s = set()

a = input("Enter a number : ")
s.add(int(a))
a = input("Enter a number : ")
s.add(int(a))
a = input("Enter a number : ")
s.add(int(a))
a = input("Enter a number : ")
s.add(int(a))
a = input("Enter a number : ")
s.add(int(a))
a = input("Enter a number : ")
s.add(int(a))
a = input("Enter a number : ")
s.add(int(a))

print(s)